### ISSUE TITLE
Chalkboom progress not saved when redemptions done mid game

### ISSUE THREAD

**Issue by jaspermayone** [FiniteSingularity/finitebot#1]

**Comment by FiniteSingularity** [comment]
If a chalk-board event occurs (e.g.- writing on the wall point redemption, raid, sub, etc..), and a game of chalk-boom is on-going, the chalk-boom game will be interrupted.  Re-configure bot to queue events until the chalk-boom scene is exited.

**Comment by FiniteSingularity** [comment]
Fixed with commit 0f026
